add PutExistFile function
Baseflow/flutter_cache_manager pull request #201
Opened 2020-07-15 07:20 UTC by shadox2003

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
feature

### :arrow_heading_down: What is the current behavior?
put file to cache has to transform file into bytes
### :new: What is the new behavior (if this is a feature change)?
copy exist file to cache

### :boom: Does this PR introduce a breaking change?
no

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cache_manager/blob/develop/CONTRIBUTING.md))
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

2020-07-16 11:31 UTC, renefloor requested changes

2020-07-16 11:31 UTC, renefloor commented on flutter_cache_manager/lib/src/cache_manager.dart
> +      await source.rename(p.join(fileDir.path, cacheObject.relativePath));
I think it is not a good idea to rename the existing file. It could be that other parts of the code rely on the file to have a certain name or be in a certain location. Either store the current name in the CacheObject or always copy the file to a new name. I'm not sure which is the best actually. I think it is better to always copy the file as the cache store has the right information on the right file. Otherwise the file might be changed by something else and the cache info isn't up to date anymore. Also the file might be cleaned by the cache logic while it isn't meant to be cleaned by the user of the library.

2020-07-17 03:40 UTC, shadox2003 commented on flutter_cache_manager/lib/src/cache_manager.dart
> +      await source.rename(p.join(fileDir.path, cacheObject.relativePath));
I think you are totally right！

2020-10-01 13:02 UTC, renefloor commented
I adapted some code to work with the new develop branch and I added some testing (you didn't write any tests right?). For the test to work I couldn't use the file path, but I don't think the stream/sink method really uses more memory?

2020-10-01 14:09 UTC, renefloor approved these changes

2020-10-01 14:09 UTC, merged