remove need for package:image to shrink package size
Baseflow/flutter_cache_manager pull request #319
Opened 2021-05-29 00:43 UTC by fzyzcjy

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
feature

### :arrow_heading_down: What is the current behavior?
see https://github.com/Baseflow/flutter_cache_manager/issues/310

### :new: What is the new behavior (if this is a feature change)?
see https://github.com/Baseflow/flutter_cache_manager/issues/310

### :boom: Does this PR introduce a breaking change?
no

### :bug: Recommendations for testing
n/a

### :memo: Links to relevant issues/docs
https://github.com/Baseflow/flutter_cache_manager/issues/310

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cache_manager/blob/develop/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

2021-06-16 11:45 UTC, renefloor requested changes
There are some failing tests, by running the tests I found at least 1 bug, but I don't have all tests running yet.

2021-06-16 11:45 UTC, renefloor commented on flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart
> +  final image = ResizeImage(FileImage(file), width: width, height: height, allowUpscaling: allowUpscaling);
In line 76 you call this without any width or height and that's not allowed for ResizeImage
```suggestion
  var shouldResize = width != null || height != null;
  var fileImage = FileImage(file);
  final image = shouldResize
      ? ResizeImage(fileImage,
          width: width, height: height, allowUpscaling: allowUpscaling)
      : fileImage as ImageProvider;
```

2021-06-16 12:21 UTC, renefloor commented on flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart
> +    var resized = await _decodeImage(originalFile.file, width: maxWidth, height: maxHeight, allowUpscaling: true);
Do you think `allowUpscaling` makes sense? I think we should not store larger files than the original. I think if maxHeight and maxWidth are larger than the originals we should just skip resizing.

2021-06-16 13:36 UTC, renefloor commented on flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart
> +    image.evict();
I added an evict, as we really only need the image bytes and can get rid of the image provider. What do you think? I think this helps a lot with memory management.

2021-06-16 13:37 UTC, renefloor commented
I played around a bit with using this in a listview with images and it is way more performing :)

2021-06-16 13:52 UTC, fzyzcjy commented on flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart
> +    var resized = await _decodeImage(originalFile.file, width: maxWidth, height: maxHeight, allowUpscaling: true);
Good question, I think you are right.

2021-06-16 13:54 UTC, fzyzcjy commented on flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart
> +    image.evict();
Sure. I think that is quite reasonable, as this will avoid polluting hte image buffers.

2021-06-16 13:54 UTC, fzyzcjy commented
> @renefloor I played around a bit with using this in a listview with images and it is way more performing :)

Happy to hear that!

2021-06-16 14:12 UTC, renefloor commented on flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart
> +    var image = await _decodeImage(originalFile.file);
What do you think of checking this instead of only setting allowUpscaling to false? 
This prevents saving the same file twice on disk.
```suggestion
    var image = await _decodeImage(originalFile.file);
    
    var shouldResize = maxWidth != null ? image.width > maxWidth : false ||
    maxHeight != null ? image.height > maxHeight : false;
    if (!shouldResize) return originalFile;
```

2021-06-16 14:14 UTC, fzyzcjy commented on flutter_cache_manager/lib/src/cache_managers/image_cache_manager.dart
> +    var image = await _decodeImage(originalFile.file);
Sounds quite reasonable!

2021-06-16 14:29 UTC, renefloor approved these changes

2021-06-16 14:30 UTC, renefloor commented
@fzyzcjy I think it's ready to be merged. Do you agree?

2021-06-17 00:04 UTC, fzyzcjy commented
@renefloor Sure!

2021-06-17 06:48 UTC, merged

2021-06-23 12:51 UTC, britannio commented
Great work! I've found this to be significantly more performant than the previous implementation!

2021-06-23 12:52 UTC, fzyzcjy commented
@britannio Happy to hear that!

2021-06-24 08:33 UTC, fzyzcjy commented
By the way, I upgrade the dependency in my production app. Now the apk size reduces by 350KB! :D