Fix removeCacheFile
Baseflow/flutter_cache_manager pull request #469
Opened 2024-09-23 07:47 UTC by SmartVive

### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
fix removeCacheFile

### :arrow_heading_down: What is the current behavior?
removeCacheFile not working. because file dir is wrong.

### :new: What is the new behavior (if this is a feature change)?
removeCacheFile is working. 

### :boom: Does this PR introduce a breaking change?
no

### :bug: Recommendations for testing

### :memo: Links to relevant issues/docs

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines ([code style guide](https://github.com/Baseflow/flutter_cache_manager/blob/develop/CONTRIBUTING.md))
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

2024-09-25 09:39 UTC, snoopdoggy322 commented
@martijn00  pls merge it, clearing cache and files doesn't work at all

2024-09-25 10:37 UTC, martijn00 requested changes

2024-09-25 10:37 UTC, martijn00 commented on flutter_cache_manager/lib/src/cache_store.dart
> +    final file = await fileSystem.createFile(cacheObject.relativePath);
I'm not sure this is correct. The old code only creates a reference to the file, and this code actually creates the file. So the check for the file will always be true, which is not correct.

Might there be a problem in your own code?

2024-09-25 11:25 UTC, snoopdoggy322 commented on flutter_cache_manager/lib/src/cache_store.dart
> +    final file = await fileSystem.createFile(cacheObject.relativePath);
@martijn00 
But the file reference leads to old code that never points to the actual file, resulting in a constant accumulation of files in the cache.

Is there a possible mistake in the name of the method itself? For example, the _fileExists method uses the same fileSystem.createFile to check for the existence of a file.

2024-09-25 12:58 UTC, SmartVive commented
test code:
```
    final oldFile = io.File(cacheObject.relativePath);
    print("oldFilePath:${oldFile.path},isExist:${await oldFile.exists()}");

    final newfile = await fileSystem.createFile(cacheObject.relativePath);
    print("newFilePath:${newfile.path},isExist:${await newfile.exists()}");
    
    final testfile = await fileSystem.createFile("test");
    print("testFilePath:${testfile.path},isExist:${await testfile.exists()}");
```

result:
```
oldFilePath:340d19b0-7b3d-11ef-ba62-6f906510429c.file,isExist:false

newFilePath:/data/user/0/xxx.xxx.xxx/cache/response/340d19b0-7b3d-11ef-ba62-6f906510429c.file,isExist:true

testFilePath:/data/user/0/xxx.xxx.xxx/cache/response/test,isExist:false
```

1.`cacheObject.relativePath` is file name. not file path
2.`fileSystem.createFile("test")`  file will not be created

@martijn00

2024-10-08 20:55 UTC, wyyadd commented
Same problem. File will never be deleted.

``` dart
final file = io.File(cacheObject.relativePath);
 if (file.existsSync()) {
}
```

Previous code will fix that.
```dart
final file = await fileSystem.createFile(cacheObject.relativePath);
```

2024-10-09 07:45 UTC, martijn00 commented
Reference https://github.com/Baseflow/flutter_cache_manager/pull/387

2024-10-09 07:45 UTC, martijn00 commented
@SmartVive can you add some more tests to make sure the behaviour is verified?

2024-10-09 14:13 UTC, SmartVive commented
@martijn00 Do you mean adding unit tests? I did, but I'm not good at them.

2024-10-09 18:50 UTC, merged

2025-04-09 08:17 UTC, dayoul commented
@martijn00 It seems like this PR is still not merged to `main` branch of this repo. Since this causes security issue among my clients, please consider merging it to `main`.

2026-07-27 21:11 UTC, rickdijk commented
@dayoul it's merged into main now!